kind: Deployment
apiVersion: apps/v1
metadata:
  name: jira-issue-refinement-evaluator
  namespace: vsphere-infra-helpers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-issue-refinement-evaluator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jira-issue-refinement-evaluator
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: container
          command:
            - python
          env:
            - name: HOME
              value: /usr/app/src
          securityContext:
            privileged: true
          ports:
            - containerPort: 8001
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: training-data
              readOnly: true
              mountPath: /training
          terminationMessagePolicy: File
          image: ''
          args:
            - main.py      
      volumes:
        - name: training-data
          secret:
            secretName: jira-issue-refinement-training
            defaultMode: 384
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
